# Generated by Django 5.0.2 on 2024-02-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion',
            name='completion_time',
            field=models.DurationField(),
        ),
    ]
