# Generated by Django 5.0.2 on 2024-02-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_completion_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion',
            name='completion_time',
            field=models.IntegerField(),
        ),
    ]
